### ISSUE TITLE
Update Repository Issue Templates

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#10]
**Is your feature request related to a problem? Please describe.**

The issue templates for this repository are intended for code management, not design oriented issue.

**Describe the solution you'd like**

Update issue templates to cover the various design oriented topics we intend to cover in this repository.

- [ ] Determine Issue Use Cases
- [ ] Create Issue Templates
- [ ] Review Issue Templates
- [ ] Implement new issue Templates

**Comment by jordanpadams** [comment]
closing new solution with HDS coming soon...
