### ISSUE TITLE
Create "Explore our Data Archive" module for homepage

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#100]
### 💡 Description

The "Explore our Data Archive" module needs to be created for the homepage.  See Figma for MVP designs.

This module is also known as "Topic Card Section, 6-Up (Explore)"

**Comment by anilnatha** [comment]
@tloubrieu-jpl Since you're having issues with ZenHub during our standup, just wanted to provide status here that I'm currently working on this ticket.

**Comment by anilnatha** [comment]
<img width="1626" alt="image" src="https://github.com/user-attachments/assets/eb329b03-1386-4650-bda5-c08d07529c21">

As one can see above, we've made progress on this module which has consisted of:

1) Adding the infrastructure for the module itself housed in a new component called `ExploreTopicsSixUp`
2) Created a new `Tabs` Component
3) Refactored our existing `Card` Component
4) Added configuration to handle responsiveness

Outstanding items as of now:

1) Create new button component
2) Create "text" card component variant
3) Update card responsiveness behavior 
4) Fix button spacing issue
5) Fix tab bar's glitch when hovering

**Comment by nutjob4life** [comment]
This (and related issues) will have PRs shortly
