### ISSUE TITLE
Create "Embedded Search" module for homepage

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#102]
### 💡 Description

The "embedded search" module needs to be created for the homepage. See Figma for MVP designs.

**Comment by eddiesarevalo** [comment]
[Uploading... Screenshot 2024-09-10 at 12.46.22 PM.png]

**Comment by eddiesarevalo** [comment]
<img width="884" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUxGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4794e15ef5ee4a49003a9bc383a0db6370426747/Screenshot%202024-09-10%20at%2012.46.22%E2%80%AFPM.png" alt="Screenshot 2024-09-10 at 12.46.22 PM.png" />

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo has questions on the design.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo made a lot of updates here since the latest meetings.

**Comment by nutjob4life** [comment]
Almost done! Just needs some styling, some minor grid issues, length of input boxes—will figure it out and merge with what @anilnatha has

**Comment by eddiesarevalo** [comment]
Added styling and responsiveness: 5b1ab8c1a610699e56cd2b876b7fe6c04e31c4d5
Merged with home page components: d6801727fbc7ff5afb8e5ceb5fac772e83261d79
