### ISSUE TITLE
Add Accordion Actions Bar design element

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#14]
**Is your feature request related to a problem? Please describe.**

Our accordion components lack an action bar component where designers can add call to actions elements. For reference, see the example shown here: https://material-ui.com/components/accordion/#secondary-heading-and-columns

**Describe the solution you'd like**

Create an action bar, similar to the action bar implemented for cards that allows designers to add call to action buttons to accordions.

**Describe alternatives you've considered**

None

**Additional context**

None

**Applicable requirements**

None.

**Comment by jordanpadams** [comment]
closing new solution with HDS coming soon...
