### ISSUE TITLE
Add bold heading typography styles

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#15]
**Is your feature request related to a problem? Please describe.**

We do not have bold any bold styles in our Typography specs.

**Describe the solution you'd like**

After speaking with @edwardbarraza about this issue, he and I agreed that we would add in bold variants for the H1-H6 font styles.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Applicable requirements**

N/A

**Comment by anilnatha** [comment]
@edwardbarraza I've added the bold typography styles, please review when you have a moment before I publish.  Or we can review during our UX tag up tomorrow.

**Comment by edwardbarraza** [comment]
Just reviewed them. They look good. Publish!

**Comment by anilnatha** [comment]
Thanks @edwardbarraza . they are published.
