### ISSUE TITLE
Review NASA HDS Wordpress code and documentation

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds#18]
## 💡 Description

Review their docs and code and setup dev environment

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo is initiating a PDS version of the HDS Wordpress from a clone of the NASA HDS Wordpress.

He's creating a README on how to initiate a development environment for this new repository.

**Comment by eddiesarevalo** [comment]
The dev environment instructions are on the wordpress repo here: https://github.com/NASA-PDS/wds-wordpress/tree/hds-wordpress

**Comment by tloubrieu-jpl** [comment]
100 commits have been done in the HDS repository since @eddiesarevalo pushed the code.

**Comment by jordanpadams** [comment]
initial review complete. code deployed locally
