### ISSUE TITLE
Plan and Prioritize needed WDS improvements and adaptations

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds#19]
## 💡 Description

Per NASA-PDS/design-team#124 and latest high fidelity designs:
- [ ] document new and adapted components of WDS
- [ ] plan and prioritize components to be implemented to support prototypes

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo @edwardbarraza @anilnatha can you work on that this Thursday.

We need:
1. the list of Horizon WDS components (Edward)
2. the list of components that PDS needs (Anil, Edward, all)

We then need to match them and identify the components that PDS needs but are not available in the Horizon WDS and prioritize among them which one should be developed first (@jordanpadams ).

Additionally we can consider that not all Horizon components are yet implemented in the WordPress WDS (which does not make things more simple...)

**Comment by jordanpadams** [comment]
Initial prioritization completed on airtable.
Modules: https://airtable.com/applgnSo7ROCVIjbd/tblejMpWgnenm4Ewy/viwDnLooTaTBpGA6u?blocks=hide
Templates: https://airtable.com/applgnSo7ROCVIjbd/tblI55g6F6Zw4uXpG/viwiIaUqnX8h1nq1s?blocks=hide
