### ISSUE TITLE
Add other organizational logos

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#2]
**Is your feature request related to a problem? Please describe.**

From time to time, a developer may need to feature the logo of an organization that has partnered with PDS. To avoid issues with correct logo usage, it may be beneficial to provide these logos in the design system.

**Describe the solution you'd like**

Provide organization logos to developers for use on PDS websites so that developers do not have to search for and create logos.

**Describe alternatives you've considered**

TBD

**Additional context**

TBD

**Applicable requirements**

TBD

**Comment by jordanpadams** [comment]
closing new solution with HDS coming soon...
