### ISSUE TITLE
Initial Data Search Journey Prototype

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#22]
## 💪 Motivation
I want to be able to search the PDS from a PDS search page.

## 📖 Additional Details
A search PDS React app that will live inside NASA's Wordpress.
Empty state PDS mock up page will be provided by @edwardbarraza 

We must be flexible about this as the new NASA wordpress mentions that they will support embedding apps. However the details for this have not yet been made available. https://website.nasa.gov/hds/modules/eyes-on-the-solar-system-embed/

## ⚖️ Acceptance Criteria
**Given** some text
**When I perform** a search
**Then I expect** relevant PDS data results

## ⚙️ Engineering Details
The app will be a react app. 
Any text entered into the search will be sent to the search API
All results returned by the API will be shown in accordance with the mockups

**Comment by jordanpadams** [comment]
:calendar: December status: In work. On schedule

**Comment by jordanpadams** [comment]
📆 January status: In work and progress ongoing. Delayed 2 sprints as scope has increased to support design system. no impact on delivery

**Comment by jordanpadams** [comment]
📆 February Status: Task ongoing and on schedule

**Comment by jordanpadams** [comment]
sub-tasks for initial implementation completed for B13.1. will be demoed at next sprint review in 2 weeks. next phase for B14.0 picks up here: https://github.com/NASA-PDS/wds-implementation/issues/37
