### ISSUE TITLE
Add Routing For Searches

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#24]
## 💪 Motivation
Allow saving searches.

## 📖 Additional Details
In order to allow saving searches and sharing these links we need to enable routing.  The router needs to be added. 

## ⚖️ Acceptance Criteria
Doing a search will save the search to the url. Copy paste the url into a new tab or browser. The same results will show.

## ⚙️ Engineering Details
We will add a react router that will add any search text as a query to the url. When the app is started the url will be parsed for these queries using react router.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo is still working on that.

**Comment by tloubrieu-jpl** [comment]
The pull request is ready to be created
