### ISSUE TITLE
Show Search Results From API

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#25]
## 💪 Motivation
Present search results with PDS styling.

## 📖 Additional Details
Update state with search results. Show these results with the PDS styling and format. The PDS styles will have to be created. 

## ⚖️ Acceptance Criteria
Entering some text into the search box and pressing enter will show any results. They will be styled according to the mock ups and PDS WDS.

## ⚙️ Engineering Details
Use saga to store the results in the state and show when updated.
Add the styles to the theme.

**Comment by jordanpadams** [comment]
@eddiesarevalo status: working these styles out with material UI

**Comment by jimmie** [comment]
still working styles

**Comment by tloubrieu-jpl** [comment]
For now, @eddiesarevalo worked from a static result page and it works. He is now blocked because the API is not accessbile from a cross origin domain (CORS configuration).

**Comment by eddiesarevalo** [comment]
CORS issue solved. Now connected to API

**Comment by eddiesarevalo** [comment]
Added Card and connected to API at https://pds.nasa.gov/api/search-en-gamma/1.1/
<img width="375" alt="Screen Shot 2022-11-29 at 12 37 21 PM" src="https://user-images.githubusercontent.com/5596893/204643656-bd1a9509-7701-4d58-9e26-48b7becf4687.png">

On hover (animated zoom and hand pointer):
<img width="373" alt="Screen Shot 2022-11-29 at 12 45 02 PM" src="https://user-images.githubusercontent.com/5596893/204643886-dadfff27-dbb9-4c8a-825a-02943bab8fcd.png">

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo will move the code to wds-react repo. The component does not need to be re-useable yet, that can be a prototype thing.

**Comment by eddiesarevalo** [comment]
Will continue review in NASA-PDS/wds-implementation#26
