### ISSUE TITLE
Integrate Search Results Feedback

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#26]
## 💪 Motivation
First version of the search results has been created in NASA-PDS/wds-implementation#23. Will review with the designers to see what should be changed.

## 📖 Additional Details
Will update this once the details have been reviewed.

## ⚖️ Acceptance Criteria
See sub-tasks for what needs to be reviewed for closeout

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo has a meeting with @anilnatha to review the prototype style

**Comment by eddiesarevalo** [comment]
I met with Anil. The results are an older version it should look like this:![Screen Shot 2022-12-13 at 3.08.38 PM.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/5079da9c-9669-46a4-ab7a-68c6abaed8d7)

The icons are custom. We will have to figure out how to use them in svg.

The columns alignments should match. This isn't reflected in the mockup but will use best judgement.

The pagination at the bottom is not yet complete. Will hold off on that for now.

When the left arrow icon is pressed it should expand to show more details.
