### ISSUE TITLE
Add Starter WDS-PDS Icons To WDS-React

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#27]
Allow for the icons for pds-wds to be used in react. 

This is the wds-page that shows the icons: 
https://www.figma.com/file/QqXo2XsUrKVu7KVjOHVeHk/PDS-Design-Library?node-id=273%3A6&t=JuaJ8bcQm7qFMASP-0

![Screen Shot 2023-01-04 at 9 19 12 AM](https://user-images.githubusercontent.com/5596893/210612784-1f97dd50-a98c-44af-8fca-13b1db9617c4.png)

**Comment by jordanpadams** [comment]
per discussion earlier today, will move this back to Release Backlog to hopefully leverage other effrots

**Comment by anilnatha** [comment]
@eddiesarevalo This was completed as we have the icons you had integrated into `wds` and `wds-react`.  Can we close this ticket?

**Comment by eddiesarevalo** [comment]
@anilnatha Yes, these were merged already in https://github.com/NASA-PDS/wds/pull/19/ Closing this.
