### ISSUE TITLE
Allow Expanding Search Result Items To Show More Details

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#28]
Clicking on the arrow button will expand a result item to show its details.
![Screen Shot 2023-01-04 at 9 25 09 AM](https://user-images.githubusercontent.com/5596893/210613736-e21f3ea5-2b0f-4f47-abf4-cbaabfea9d32.png)

**Comment by eddiesarevalo** [comment]
Added in pds-wds-react: https://github.com/NASA-PDS/wds-react/commit/4541099c28c8fe8cd56de5cd62cd9a3f3d6c58ef

**Comment by jordanpadams** [comment]
Going to call this task complete for now and review will occur we close out its parent epic #26

**Comment by tloubrieu-jpl** [comment]
Hi @eddiesarevalo , can you add an estimate for this ticket ? Thanks
