### ISSUE TITLE
Update Search Result Component Alignments

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#29]
Fix the alignments. Many of the items in the prototype mockup are off. Will use best judgement.
![Screen Shot 2023-01-04 at 9 20 20 AM](https://user-images.githubusercontent.com/5596893/210613331-442950fa-f36b-4cbd-bdb7-343d8dc18435.png)

**Comment by eddiesarevalo** [comment]
Corrected the alignments in pds-wds-react: https://github.com/NASA-PDS/wds-react/commit/8ef932a9a0e2ed159f4251453e60a6c87aa4f856

**Comment by jordanpadams** [comment]
Going to call this task complete for now and review will occur we close out its parent epic #26

**Comment by tloubrieu-jpl** [comment]
Hi @eddiesarevalo can you add an estimate for this ticket ? Thanks
