### ISSUE TITLE
Add Tag Component

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#30]
### Checked for duplicates

Yes - I've already checked

### Related problems

The **Chip** component is currently being used. It should be a **Tag** component instead. The tag should be styled to PDS-WDS.

From this:
![Screen Shot 2023-01-19 at 9 15 35 AM](https://user-images.githubusercontent.com/5596893/213514698-780cbdb6-b873-4ce8-8624-d57c3fec0908.png)

To this:
![Screen Shot 2023-01-19 at 9 18 34 AM](https://user-images.githubusercontent.com/5596893/213514980-a16ec937-7dd2-4872-9ef0-54846f337a6b.png)

### 🧑‍🔬 User Persona(s)

Everyone

### 💪 Motivation

Need a tag component for the search prototype.

### 📖 Additional Details

None

### Acceptance Criteria

Chip will be replaced with tag and have PDS styling.

### ⚙️ Engineering Details

Provide some design / implementation details and/or a sub-task checklist as needed. Convert issue to Epic if estimate is outside the scope of 1 sprint.

**Comment by jimmie** [comment]
replace chip component w/ tag component in progress

**Comment by eddiesarevalo** [comment]
Added Tag component in https://github.com/NASA-PDS/wds-react/commit/3b0976f39fc483c576300abb68e4109bf64c4a9e

**Comment by jordanpadams** [comment]
Going to call this task complete for now and review will occur we close out its parent epic #26
