### ISSUE TITLE
Refactor Search Prototype Into Components

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#31]
### Checked for duplicates

Yes - I've already checked

### Related problems

The search protoype has built components that need to be separated into their own components.

### 🧑‍🔬 User Persona(s)

Developers

### 💪 Motivation

Components need to be separated out so they can be easily imported and used when necessary. Currently some of them are bundled together.

### Acceptance Criteria

Components like SearchField, Textfield and Card need to be in separte files and easily imported using syntax similar to `import Tag from './Tag'`

### ⚙️ Engineering Details

- [x] SearchField
- [x] TextField
- [x] Card

**Comment by eddiesarevalo** [comment]
Code separated out in https://github.com/NASA-PDS/wds-react/commit/10d61aac697a6ba63fcfb20d5229ac9b64061f13

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo needs to meet with Anil and Edward to review that change

**Comment by eddiesarevalo** [comment]
Met with Anil and Edward. A couple of notes.

-textfield will have an arrow icon and will also allow an "x" to clear.
-search result item is a component.
-http request loading and fail will need to be designed.

The only action item is to make the search result item into a component.
