### ISSUE TITLE
Add sorting buttons

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#34]
Add the sorting buttons to the search prototype

<img width="912" alt="Screenshot 2023-02-16 at 1 04 23 PM" src="https://user-images.githubusercontent.com/5596893/219486720-e50c2516-3390-48e9-b7d8-8302fc2f01cc.png">

**Comment by eddiesarevalo** [comment]
Added in https://github.com/NASA-PDS/wds-react/commit/97f0112857283bb932a65538a0aab21447dc8720
![Screenshot 2023-03-02 at 1.37.04 PM.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/2e1d924d-36dd-4400-b9d0-9e86691af7ac)

**Comment by tloubrieu-jpl** [comment]
Note that the API back-end does not implement that, so there is no effect with this widget.
