### ISSUE TITLE
Update Featured Link List Item Types

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#36]
## 💡 Description
Featured link list item currently appears the same for all data types. It must be updated to look different for documentation, tool and data.

For example documentation should look like this:
<img width="481" alt="Screenshot 2023-03-14 at 9 08 17 AM" src="https://user-images.githubusercontent.com/5596893/225067307-d795ca9c-b36f-4137-b220-8a421a45425c.png">

Tool should look like this:
<img width="451" alt="Screenshot 2023-03-14 at 9 08 09 AM" src="https://user-images.githubusercontent.com/5596893/225067465-1bf708e4-e919-4c85-8f93-bbc6f97020f3.png">

**Comment by tloubrieu-jpl** [comment]
I created a follow up ticket to find the properties which describe the documents and data tab, see https://github.com/NASA-PDS/wds-react/issues/89
