### ISSUE TITLE
Create Side Filters

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#38]
@eddiesarevalo commented on [Tue Mar 28 2023](https://github.com/NASA-PDS/wds-react/issues/86)

Create the filters that go on the left side of the screen.

Design:

<img width="281" alt="Screenshot 2023-03-28 at 8 30 56 AM" src="https://user-images.githubusercontent.com/5596893/228291534-70e07dd6-7d09-4d4e-9ad4-17dd99506885.png">

Full Page:
<img width="676" alt="Screenshot 2023-03-28 at 8 31 17 AM" src="https://user-images.githubusercontent.com/5596893/228291615-5a2f9b10-ecc2-43f1-83a5-ca07007041b5.png">

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo is making good progress on that.

**Comment by tloubrieu-jpl** [comment]
This ticket is almost done except for a few styles.

**Comment by eddiesarevalo** [comment]
Pull request at https://github.com/NASA-PDS/wds-react/pull/90
