### ISSUE TITLE
Create Breadcrumb Component

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#40]
## 💡 Description
Create the breadcrumb component and add it to the search prototype.

This component in the top left. Has a couple of labels:
<img width="1047" alt="Screenshot 2023-05-24 at 1 43 29 PM" src="https://github.com/NASA-PDS/wds-implementation/assets/5596893/fe43b2da-503d-4d2a-974c-1acc0830877e">

<img width="535" alt="Screenshot 2023-05-24 at 1 43 54 PM" src="https://github.com/NASA-PDS/wds-implementation/assets/5596893/c1a2f7f4-0825-4e9a-9c71-4108fbb78a8b">

<img width="954" alt="Screenshot 2023-05-24 at 1 45 50 PM" src="https://github.com/NASA-PDS/wds-implementation/assets/5596893/6236874e-fb8a-403f-9c56-8bc567b5014c">

**Comment by tloubrieu-jpl** [comment]
Hi @anilnatha , can you look at this ticket. It is mostly done but I had one or two comments on the PR https://github.com/NASA-PDS/wds-react/pull/98
