### ISSUE TITLE
As a developer, I want to deploy a local instance of headless wordpress and latest code using Docker

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#43]
### Checked for duplicates

No - I haven't checked

### 💪 Motivation

We need a headless wordpress environment so that developers can use it to implement our new site.

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
@anilnatha is working on the wordpress deployment in a docker container.

**Comment by tloubrieu-jpl** [comment]
This is still the priority for @anilnatha

**Comment by tloubrieu-jpl** [comment]
@anilnatha is looking at how to manage custom data types.

**Comment by tloubrieu-jpl** [comment]
@anilnatha solved an issue related to loading CSS in wordpress pages.

**Comment by tloubrieu-jpl** [comment]
Only the docker for the front-end does not run. For now @anilnatha in development mode does not run that part in docker.

**Comment by anilnatha** [comment]
- [ ] Need to update README documentation so this ticket can be closed. Documentation should include the present issues with dockerizing the frontend service

**Comment by jordanpadams** [comment]
@anilnatha any status on updating the README so we can close this out?

**Comment by anilnatha** [comment]
Created a PR that includes the instructions. As we know we still have a ways to go with the services, but the instructions at least document how to get what we have running locally. Will need to update these once we can get the SMD codebase running locally and we migrate their services into our configuration.

**Comment by jordanpadams** [comment]
Still has some issues, but per https://github.com/NASA-PDS/portal-wp/pull/3, considering this closed for now
