### ISSUE TITLE
Why headless over vanilla Wordpress?

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds#45]
## 💡 Description

Create a quick write-up on why headless WP versus "vanilla" WP. This can be put in either Markdown file in the repo itself or in the repo wiki.

**Comment by jordanpadams** [comment]
@anilnatha as a heads up, we have this in the sprint backlog if you have a chance to write something up. Can either toss it in a Markdown file in the repo or on a wiki page on the repo.

**Comment by jordanpadams** [comment]
@anilnatha can we get a quick writeup for this before the end of this sprint (next Thursday)?

**Comment by anilnatha** [comment]
@jordanpadams Yes! I'll get this put together before Thursday.

**Comment by jordanpadams** [comment]
Closed per https://github.com/NASA-PDS/portal-wp/pull/2
