### ISSUE TITLE
Implement Header

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#49]

**Comment by jordanpadams** [comment]
@anilnatha working on this tag for initial prototype

**Comment by anilnatha** [comment]
Looking good so far, implementing CSS styling

![image](https://github.com/NASA-PDS/portal-wp-tasks/assets/931107/2dc65139-0696-4ea5-99ec-7047cbc0afd4)

<img width="360" alt="image" src="https://github.com/NASA-PDS/portal-wp-tasks/assets/931107/030d9fbd-a113-4e4f-a05e-e00c2f17d131">

<img width="740" alt="image" src="https://github.com/NASA-PDS/portal-wp-tasks/assets/931107/4298e253-72e7-405f-a757-b85dfd99ede2">

**Comment by anilnatha** [comment]
Completed first iteration of titlebar and navbar component inside our frontend prototype:

### "XL" breakpoint:

<img width="1692" alt="image" src="https://github.com/NASA-PDS/portal-wp-tasks/assets/931107/c851afb5-8300-48c9-b72b-06d32b25fc79">

### "L" breakpoint:

<img width="1362" alt="image" src="https://github.com/NASA-PDS/portal-wp-tasks/assets/931107/6c7d1fe0-c44c-4b24-bf6e-2ff8a71ece5e">

### "M" breakpoint:

<img width="1155" alt="image" src="https://github.com/NASA-PDS/portal-wp-tasks/assets/931107/68a445d9-c8e8-40a3-bb31-55b3132e0a1f">


### "S" breakpoint:

<img width="819" alt="image" src="https://github.com/NASA-PDS/portal-wp-tasks/assets/931107/2394b064-3f93-4d5b-81bb-00e8fc186e10">

Remaining items are to integrate and style menus, add polish to typography styles, update iconography

**Comment by jordanpadams** [comment]
📆 October status: Header implementation in work several remaining items to be completed in the next sprint. No foreseeable impact on build.

**Comment by jordanpadams** [comment]
@anilnatha where are we at with the Header component? Do we think we can call this first iteration complete?

**Comment by jordanpadams** [comment]
Initial implementation completed

**Comment by anilnatha** [comment]
Yes, we can consider this first iteration complete, the menu styling was intended to be completed later.
