### ISSUE TITLE
Implement Navbar

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#50]

**Comment by tloubrieu-jpl** [comment]
Hi @anilnatha , I think this has been done for some time now. Is there are related pull request that we can attach this ticket to ?

**Comment by tloubrieu-jpl** [comment]
Oh, @anilnatha, I guess it is in the develop branch of the wds-react repository. To track the realization of the tickets it is convenient however to link them to something in the code, a commit reference or a pull request. 
We also want a peer review on the developed feature would that be a validation/review on the `develop` branch and once the validation is done we merge to `main` and close the ticket ?

**Comment by jordanpadams** [comment]
@anilnatha Can we add a commit or PR for this? Are we committing directly to `develop`?

**Comment by anilnatha** [comment]
@jordanpadams This was added to the portal-wp prototype which is in it's respective 'develop' branch which was handled via [this PR](https://github.com/NASA-PDS/portal-wp/pull/1), the tickets were linked in the PR. 

This ticket and the accompanying [ticket for the title bar](https://github.com/NASA-PDS/portal-wp-tasks/issues/51) weren't closed when the PR was reviewed/merged.

**Comment by anilnatha** [comment]
Closing this ticket, additional enhancements are being handled in this [ticket](https://github.com/NASA-PDS/portal-wp-tasks/issues/55).

**Comment by jordanpadams** [comment]
@anilnatha excellent! Thanks!
