### ISSUE TITLE
Implement Titlebar (logo, node navigation, search)

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#51]

**Comment by jordanpadams** [comment]
@anilnatha this is in Review/QA, but do we have a commit or a PR for this?

**Comment by anilnatha** [comment]
> @anilnatha this is in Review/QA, but do we have a commit or a PR for this?

Yup, see [this comment](https://github.com/NASA-PDS/portal-wp-tasks/issues/50#issuecomment-1899301863)

I'm going to close this ticket as it was done. Additional work is tracked [here](https://github.com/NASA-PDS/portal-wp-tasks/issues/55).
