### ISSUE TITLE
Create new wds-react repo and migrate code from legacy repo

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#54]
Since we decided to rename the current `wds-react` repo to `wds-react-legacy`, we can move forward with a clean slate regarding the new version of the `wds-react` package by:

- [x] Creating a new repo named `wds-react`
- [x] Migrating the code for the new version of this package from the legacy repo
- [x] Testing the build against the prototype by trying `npm link`

**Comment by anilnatha** [comment]
The new `wds-react` repository has been created and I've migrated code into the `develop` branch of this repo so that I can continue working on our prototype.

**Comment by jordanpadams** [comment]
Done. New repo created
