### ISSUE TITLE
Phase 1: Investigations Directory Page Module Implementation

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#59]
This epic describes the tasks related to the implementation of the Investigations directory page.

**Comment by nutjob4life** [comment]
@tloubrieu-jpl is assisting in writing queries for context products and how they're archived in OpenSearch … however querying for investigations, OpenSearch isn't behaving the way we expect it to

**Comment by tloubrieu-jpl** [comment]
React/Redux is now integrated in this development and will be re-usable.

@anilnatha now works on the feature list component to match the new PDS design.

**Comment by tloubrieu-jpl** [comment]
@anilnatha is integrating redux states to this page.

**Comment by tloubrieu-jpl** [comment]
Still in progress.

**Comment by anilnatha** [comment]
Wanted to list the Directory page updates I've made in this last sprint which coincided with our demo at yesterday's MC meeting.

#### Updated search capability, searches are now performed against targets and instruments in addition to investigations.
<ul>Free text search for investigations, targets, and instruments are executed against their respective titles _and_ lids.  I chose to search against lids because I felt it was a great piece of metadata since it contains acronyms and short names that many use and this information couldn't be found in other fields. It is trivial to add additional fields to search against, but there are performance costs in doing so.</ul>

#### Updated affiliate spacecraft
<ul>Created a new redux selector to fetch the investigation's related instrument host information so that instrument host names could be listed</ul>

#### Other Updates
* Breadcrumb display
* Typography and Layout refinements.

**Comment by tloubrieu-jpl** [comment]
@anilnatha is adding feedback from MC to the figma design and develops the pages for smaller screens.

Next he's going to integrate the header updates that Eddie developed.

3 components are missing on the page (inernal navigation, metadata, ...)

**Comment by jordanpadams** [comment]
Status: Working to make these queries work with the API vs. using OpenSearch. Also working on design improvements to for planned demo.

**Comment by jordanpadams** [comment]
📆 06/2024 status: In work on schedule

**Comment by jordanpadams** [comment]
Sprint Status: ongoing polish to these for the demo on Wednesday at MC.

**Comment by jordanpadams** [comment]
Investigation directory page complete
