### ISSUE TITLE
Phase 1: Investigation Landing Page Module Implementation

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#60]
This epic describes the tasks related to the implementation of the Investigations details page.

**Comment by tloubrieu-jpl** [comment]
@anilnatha is working on a loader component for this page.

**Comment by tloubrieu-jpl** [comment]
@anilnatha is developing the interactions with the opensearch database.

**Comment by tloubrieu-jpl** [comment]
issues with react-redux to be discussed with @eddiesarevalo

**Comment by tloubrieu-jpl** [comment]
@anilnatha is working on that for the Management council next week.

**Comment by tloubrieu-jpl** [comment]
Still making progress for the demo at Management council tomorrow.

**Comment by anilnatha** [comment]
Wanted to list the Detail page updates I've made in this last sprint which coincided with our demo at yesterday's MC meeting.

#### Added instrument host selection
<ul>Not only can we now select an instrument host and have the page rerender, I brought up an issue with Edward and we improved the design of the instrument host selection</ul>

#### Updated featured link components.
<ul>The look and feel of the various implementations of the featured list item components have been updated; however, more work needs to be done to improve their responsiveness.</ul>

#### Updated tab styling
<ul>Modified display of tabs so that their styles do a better job of aligning with HDS; however, because of the way Material UI builds their tabs, some design styles can't easily be adopted (e.g. spacing between label and bottom of tab can't be set to exactly the same thing as what HDS prescribes, but will be close).</ul>

#### Breadcrumb navigation
<ul>Tested new breadcrumb usage to speed up link navigation which proved to be beneficial. Need to integrate updated breadcrumb functionality into wds-react</ul>

#### Deep link tabs
<ul>Modified tab navigation so that tab updates are reflected in the address bar to support deep linking. However, this raised the need to also incorporate instrument host selection via the web address which still needs to be incorporated. In addition, the tab component needs to be pulled out and integrated into wds-react as a standlone, reusable component.</ul>

#### Other Updates
* Used a crude way of modifying the description information using string replacement
* Breadcrumb display
* Updated header component to better handle investigations will long titles
* Updated information that is fetched from OpenSearch for display on the instruments and target tabs
* Updated redux selectors to improve performance using memoized selectors where possible.
* Typography and Layout refinements.

**Comment by jordanpadams** [comment]
📆 03/2024 status: In work. On schedule

**Comment by jordanpadams** [comment]
status: see Epic sub-tickets for more details.

**Comment by tloubrieu-jpl** [comment]
@anilnatha is now adding the data bundles and other data information to the landing page.

**Comment by jordanpadams** [comment]
📆 05/2024 status: In work. Delayed 1 sprint due to demo preparation for HQ leadership. No impact on delivery.

**Comment by jordanpadams** [comment]
@anilnatha FYI, I removed this from the sprint backlog because it is too large of a task to be statusing on it's own. Let's figure out how we can chunk this work more clearly, and open/close tickets accordingly. I see there are sub-tasks here, so it may be best to use those to show progress/status.

**Comment by jordanpadams** [comment]
📆 06/2024 status: In work. Delayed 1 additional sprint due to demo preparation for HQ leadership. No impact on delivery.

**Comment by jordanpadams** [comment]
Investigation landing page complete
