### ISSUE TITLE
Create Typography component

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#68]
### 💡 Description

The Typography component is one of the few most widely used components we will need initially.

Development of this component entails:

- [x] Add the appropriate CSS classes to `wds` that codify our Typography styles defined in Figma
- [x] Add the appropriate component to `wds-react` that consume the CSS from `wds` to render the component. The component should address variants (e.g. Heading, Body, etc.) and breakpoints (e.g. 'sm', 'md', etc.)

**Comment by tloubrieu-jpl** [comment]
Eddie will complete the ticket.

**Comment by jordanpadams** [comment]
Status: Refactoring needed to wds and wds-react styling to use this component. Need to extend styles from wds in wds-react repo.

**Comment by tloubrieu-jpl** [comment]
progress on that.

**Comment by tloubrieu-jpl** [comment]
Good progress on that. Families remain to be added.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo is making changes to the props.

**Comment by eddiesarevalo** [comment]
WDS pull request https://github.com/NASA-PDS/wds/pull/24

WDS-React pull request https://github.com/NASA-PDS/wds-react/pull/25

**Comment by tloubrieu-jpl** [comment]
Waiting for review by @anilnatha
