### ISSUE TITLE
Use Typography Component In Header

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#69]
### 💡 Description

The header component needs to use the typography component to get the correct font styles.

**Comment by tloubrieu-jpl** [comment]
Some of the styles are not used in the header yet. Eddie is investigating that issue.

**Comment by tloubrieu-jpl** [comment]
All the issues are fixed, the styles are properly overiden, and other fixes are done.

linked components need to be carefully tested.

**Comment by jordanpadams** [comment]
Status: Added to header complete. portal-wp header replaced with new wds-react header. PR expected by Tuesday

**Comment by eddiesarevalo** [comment]
Pull requests 
https://github.com/NASA-PDS/wds-react/pull/31
https://github.com/NASA-PDS/portal-wp/pull/5
