### ISSUE TITLE
Add Responsiveness To Header

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#72]
### 💡 Description

Add responsiveness to header.

Bars need to resize
https://www.figma.com/design/QqXo2XsUrKVu7KVjOHVeHk/PDS-Design-Library?node-id=3919-92942&t=PjLMiN6Fl2q9rjdE-0

New menu must appear when small enough.
<img width="800" alt="Screenshot 2024-06-25 at 11 56 16 AM" src="https://github.com/NASA-PDS/portal-wp-tasks/assets/5596893/c2bbb45c-6e4d-4ec0-ac8d-2d298fa86fd9">

<img width="247" alt="Screenshot 2024-06-25 at 11 56 24 AM" src="https://github.com/NASA-PDS/portal-wp-tasks/assets/5596893/e1c1de61-47cd-4ba1-9d53-8ee113f76020">

**Comment by nutjob4life** [comment]
Working on adding responsiveness to the header; it changes in sizes depending on how big the screen is. Node home pages completed. Mobile browsing FTW

**Comment by eddiesarevalo** [comment]
Pull requests:
WDS https://github.com/NASA-PDS/wds/pull/38
WDS-React https://github.com/NASA-PDS/wds-react/pull/32

**Comment by jordanpadams** [comment]
Awaiting review and merge.

**Comment by tloubrieu-jpl** [comment]
Updated after review. Expecting new review.
