### ISSUE TITLE
Add Search Filters To Search Page

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#85]
### 💡 Description

Show filters for search page.

<img width="164" alt="Screenshot 2024-08-06 at 12 53 38 PM" src="https://github.com/user-attachments/assets/bdd31803-1c52-4044-ba57-bd3c799e4a57">

**Comment by jordanpadams** [comment]
Status: functionality is in work on getting the filters to work as expected. e.g. filter options to show continuously. content will be different from the content that is in the current keyword search endpoints.

**Comment by tloubrieu-jpl** [comment]
Eddie is making progress on that. It has been a journey.

**Comment by eddiesarevalo** [comment]
Added in https://github.com/NASA-PDS/portal-wp/commit/88ba097f00f04b322975a77f2d8e463e7fbb3752. There are more design items being worked on for filters but I'll create a new ticket to implement those changes.

**Comment by eddiesarevalo** [comment]
Merged in https://github.com/NASA-PDS/portal-wp/pull/20
