### ISSUE TITLE
Fix portal and dependency build issues

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/pds-wds#93]
### 💡 Description

There are additional build issues that need to be fixed that are blocking @nutjob4life from proceeding with working on deployments of the `portal-wp` codebase.

The build issues need to be addressed in the `wds-react` and `portal-wp` repos, and possibly the `wds` repo.

**Comment by nutjob4life** [comment]
@anilnatha thanks so much for keeping me apprised!

**Comment by jordanpadams** [comment]
Status: Awaiting review and merge to unblock tasks for @nutjob4life
