### ISSUE TITLE
Create CTA Type For Button Component 

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds#94]
### 💡 Description

Need a button component in order to build the search box.

Need the button:

<img width="779" alt="Screenshot 2024-08-07 at 9 45 36 AM" src="https://github.com/user-attachments/assets/ff12c4f0-6626-4257-b65f-edd087378004">

Styles for button go in wds. Button is a base component like typography.

For this task we only need CTA type button. We can hold off on the rest of the types until needed later.

<img width="302" alt="Screenshot 2024-08-07 at 9 48 18 AM" src="https://github.com/user-attachments/assets/a48699e4-496c-4e96-bc16-f87835682c1d">

**Comment by eddiesarevalo** [comment]
Added For WDS: https://github.com/NASA-PDS/wds/commit/0e3b09f4bb4a7e421c4671a53eb33c5e281e82da
Added For WDS-React: https://github.com/NASA-PDS/wds-react/commit/bfb114acdfc165a8d71b0940f3d7cb890ff5d957

**Comment by anilnatha** [comment]
@eddiesarevalo  This touches on other CTA stuff that I need to do as well.  Want me to take this effort on?

**Comment by eddiesarevalo** [comment]
@anilnatha Sure! I only added CTA styles for the secondary button that we use in the search bar for search page. Feel free to add anything.

**Comment by eddiesarevalo** [comment]
Merged in https://github.com/NASA-PDS/wds-react/pull/60
